export const CONTRACT_CONFIG = {
  contractId: process.env.STELLAR_CONTRACT_ID || "CBAEJOL2DHNWHV3WDYEIST5C6MS6647UK33CIPBCDO4YEV254QZQ3USO",
  tokenId: process.env.STELLAR_TOKEN_ID || "CDLZFC3SYJYDZT7K67VZ75HPJVIEUVNIXF47ZG2FB2RMQQVU2HHGCYSC",
  rpcUrl: process.env.STELLAR_SOROBAN_RPC_URL || "https://soroban-testnet.stellar.org",
};
